version: '3'

services:
  pruebaapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: prueba-docker
    container_name: prueba-app
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/prueba
    environment:
      VERSION: ${VERSION}
      PORT: ${PORT}
      URL: ${URL}
      BASE_PATH: ${BASE_PATH}
      MONGODB: ${MONGODB}
    # volumes:
    #   - ./:/var/www/prueba

  db:
    image: mongo:5
    container_name: mongo-prueba
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: db-prueba
    volumes:
      - ./mongo:/data/db